branch-defaults:
  release:
    environment: Webform-env
environment-defaults:
  Webform-env:
    branch: null
    repository: null
global:
  application_name: web-form
  default_ec2_keyname: null
  default_platform: Node.js 16
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
